#!/usr/bin/env sh

# Install czmq
env HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles brew install czmq

# Install kotlin-logging
mkdir -p kotlin-logging
cd kotlin-logging || exit
git init
git remote add origin https://github.com/MicroUtils/kotlin-logging.git
git fetch origin 7af97dbd4c79a3bf92cb4eacd4ca8abc0a6e217c
git reset --hard FETCH_HEAD
sed -i 's/\r$//' ./gradlew
chmod +x ./gradlew
./gradlew publishToMavenLocal -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m --no-daemon --stacktrace
cd ..
