# Based on https://github.com/touchlab/Stately/blob/main/.github/workflows/build.yml

name: build
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-10.15, windows-2019, ubuntu-20.04 ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - if: matrix.os == 'macos-10.15'
        run: env HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles brew install czmq
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.1.0
          java: java11
          arch: amd64
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - if: matrix.os == 'macos-10.15'
        run: chmod +x ./bootstrap && ./bootstrap
      - if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install -y libczmq-dev gcc-multilib
      - if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install -y libappindicator1 fonts-liberation
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
      - if: matrix.os == 'windows-2019'
        run: SETX PATH "%PATH%;C:\msys64\mingw64\bin"
      - run: ./gradlew build --no-daemon --stacktrace
