name: Gradle build

on: [ push ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies
        run: sudo apt install -y libczmq-dev gcc-multilib
      - name: Install Chrome
        run: |
          sudo apt install -y libappindicator1 fonts-liberation
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            **/.gradle
            **/build
          key: gradle_6_7
          restore-keys: gradle_6_7

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-linux-1.4.20-eap-80
          key: ${{ runner.os }}-konan-1.4.20-eap-80
          restore-keys: ${{ runner.os }}-konan-1.4.20-eap-80
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.daemon=false --build-cache build
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install czmq
        run: brew install czmq
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            **/.gradle
            **/build
          key: gradle_6_7
          restore-keys: gradle_6_7

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-1.4.20-eap-80
          key: ${{ runner.os }}-konan-1.4.20-eap-80
          restore-keys: ${{ runner.os }}-konan-1.4.20-eap-80
      - name: Build with Gradle
        run: sudo ./gradlew -Dorg.gradle.daemon=false --build-cache build
